image: python:3.7-alpine

stages:
  - build
  - test

services:
    - docker

build:
  stage: build
  script:
    - echo "Building..."

test:
  stage: test
  script:
    - pip install docker-compose
    - docker-compose run app sh -c "python manage.py test && flake8"
