stages:
  - build
  - test

services:
    - docker

build:
  stage: build
    - echo "Building..."

test:
  stage: test
    - echo "testing..."
  before_script:
    - pip install docker-compose
  script:
    - docker-compose run app sh -c "python manage.py test && flake8"
