image: python:3.7-alpine

stages:
  - test

services:
    - docker

test:
  stage: test
  script:
    - pip install docker-compose
    - docker-compose run app sh -c "python manage.py test && flake8"
